### ISSUE TITLE
Jsonnet + VSCODE + autocomple

### ISSUE THREAD

**Issue by Asgoret** [jsonnet-libs/k8s#10]
Hi to all. 

Can somebody help with autocomplete in vscode? I install all plugins (and autocomplete works in kubernetes-prometheus folder) but I can't import new library with autocomplete

**Comment by Asgoret** [comment]
Ok...Little investigation. I think the autocomplete problem lies somebody near imports in the library. For example:
```
local d = (import 'doc-util/main.libsonnet'),
```

And error:
```
Can't find path 'doc-util/main.libsonnet'. If the file is not in the current directory, it may be necessary to add it to the 'jsonnet.libPaths'. If you are in vscode, you can press 'cmd/ctrl-,' and add the path this library is located at to the 'jsonnet.libPaths' array
```

But I don't have `doc-util` installed at all)

**Comment by Duologic** [comment]
This is a support issue, not really part of this project.

Feel free to reach out to the Tanka community via [GitHub Discussions](https://github.com/grafana/tanka/discussions/442) or in `#tanka` on [Grafana Slack](https://grafana.slack.com).
