### ISSUE TITLE
(k8s-libsonnet) inconsistent inclusion of labelSelector

### ISSUE THREAD

**Issue by BronzeDeer** [jsonnet-libs/k8s#124]
"labelSelector" (`definitions/io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector`) is a widely referenced struct all throughout the kubernetes api. (A naive text search turns up 30 hits across the swagger.json). However, despite being referenced in many places, the actual label selector object only appears in 3 places in the generated libsonnet:
 - `core.v1.topologySpreadConstraint`
 - `core.v1.podAffinityTerm`
 - `core.v1.weightedPodAffinityTerm`
 
 Even one of the most often used selectors `core.v1.service.spec.selector` has no labelSelector obj found anywhere near it. 
 
 There is the similar `core.v1.scopeSelector`, which does only matchExpression and not matchLabel, but is included at the correct place in the generated libsonnet. scopeSelector exists in swagger.json as `definitions/io.k8s.api.core.v1.ScopeSelector`. My first instinct was to think that the apimachinery group just needs to be included in the output via the custom mechanism, similar to the list object. In this case however, I fail to understand why the 3 aforementioned objects correctly included the labelSelector definition (but no transitive definitions!), while all others failed. This might point to a bug in the generator code

**Comment by BronzeDeer** [comment]
I've created a PR to also include the meta structures in the generated libsonnet, this will make working with things like labelSelector much more ergonomic, but I'm still concerned about the possibility of a generator bug

**Comment by xvzf** [comment]
@BronzeDeer did you find a potential bug? If not, let's close this and create a new issue when a bug occurs.

**Comment by BronzeDeer** [comment]
@xvzf  I haven't look into it much deeper, the PR was merged, so if there were no more issues like this, I'm happy to close
