### ISSUE TITLE
Allow overriding podLabels' default "name" key

### ISSUE THREAD

**Issue by dave08** [jsonnet-libs/k8s#14]
Some prefer to use the k8s standard "app.kubernetes.io/name" or just "app". It seems to be hard-coded in over here for deployments, for example: https://github.com/jsonnet-libs/k8s/blob/a34cc6142bf6d8bbcff9d262d5622652ae6a9068/custom/apps.libsonnet#L34. There should either be a way of specifying the name of such a label in some global config, or just be able to override it.

**Comment by dave08** [comment]
Currently a workaround is to pass `{name:: ""}` as one of the labels to podLabels.

**Comment by fculpo** [comment]
{name:: null} is even better imo

**Comment by dave08** [comment]
Thanks alot!
