### ISSUE TITLE
Feature request: add prefix for downloaded library to avoid same version number conflict with other library

### ISSUE THREAD

**Issue by c0ffeec0der** [jsonnet-libs/k8s#143]
Currently downloaded library using jb, i.e

```
jb install github.com/jsonnet-libs/k8s-libsonnet/1.21@main
jb install github.com/jsonnet-libs/istio-libsonnet/1.13@main
```

will download the library in vendor folder as following

vendor
 |- 1.21
 |- 1.13

This convention will one day result in conflict when there are _same version number for different library_ i.e kubernetes 1.21 with istio 1.21.

To avoid such conflict, suggest the folder to add prefix

vendor
 |- k8s-1.21
 |- istio-1.21

**Comment by Duologic** [comment]
I agree this is an annoying consequence of naming and how jsonnet-bundler handles the "legacy" naming. 

Personally I see this as a problem with jsonnet-bundler and ideally should be fixed there. Changing the naming upstream (here) would be a workaround for a downstream problem. Perhaps a `jb install --name <name> <url>` pattern would be a nice feature for `jb`.

As a quick workaround, you can set the 'name' attribute in `jsonnetfile.json`:

```
...
    {
      "source": {
        "git": {
          "remote": "https://github.com/jsonnet-libs/istio-libsonnet.git",
          "subdir": "1.13"
        }
      },
      "version": "main",
      "name": "istio-lib"  <--- set name here
    },
...
```

**Comment by Duologic** [comment]
I've made a quick PR for jsonnet-bundler for this: https://github.com/jsonnet-bundler/jsonnet-bundler/pull/158 (not sure if they will take it as it is a legacy feature)

**Comment by Duologic** [comment]
That PR got merged ^^ ✨

**Comment by c0ffeec0der** [comment]
Yeah, I just saw that too! Many Thanks @Duologic :grin:
