### ISSUE TITLE
roleBinding and clusterRoleBinding: withRoleRef

### ISSUE THREAD

**Issue by fculpo** [jsonnet-libs/k8s#15]
Hi,

Is it possible to reference a role easily in roleBinding and clusterRoleBinding ?
Something similar to `clusterRoleBinding.withSubjects` https://jsonnet-libs.github.io/k8s-alpha/1.17/rbac/v1/clusterRoleBinding/#fn-withsubjects

**Comment by fculpo** [comment]
If I didn't miss something this is the easy way to do it without available mixin:

```jsonnet
    clusterRoleBinding.new($._config.name)
    + clusterRoleBinding.withSubjects(k.rbac.v1.subject.fromServiceAccount($.sa))
    + {
      roleRef: {
        apiGroup: 'rbac.authorization.k8s.io',
        kind: 'ClusterRole',
        name: 'xxx'
      }
    },
```

vs

```
clusterRoleBinding.new($._config.name)
    + clusterRoleBinding.withSubjects(k.rbac.v1.subject.fromServiceAccount($.sa))
    + clusterRoleBinding.roleRef.withApiGroup('rbac.authorization.k8s.io')
    + clusterRoleBinding.roleRef.withKind($.clusterRole.kind)
    + clusterRoleBinding.roleRef.withName($.clusterRole.metadata.name),
```

**Comment by fculpo** [comment]
Thanks a lot ! 
when / how is this change available in k8s-alpha libs?

**Comment by Duologic** [comment]
I have one more PR I need to verify here and then I'll generate a new version. Likely before the end of next week.
