### ISSUE TITLE
Generation for k8s 1.19 to k8s-alpha repo

### ISSUE THREAD

**Issue by dave08** [jsonnet-libs/k8s#16]
Just wondering if this will be done soon, or should we just use 1.18 meanwhile?

**Comment by sh0rez** [comment]
I added Kubernetes 1.19 in https://github.com/jsonnet-libs/k8s-alpha/commit/46e45906958567cdbc1b3bde181ef8bc4afb877d

**Comment by dave08** [comment]
Thanks!
