### ISSUE TITLE
 Kubernetes 1.22+ breaks docsonnet

### ISSUE THREAD

**Issue by irizzant** [jsonnet-libs/k8s#171]
This is a follow up to https://github.com/jsonnet-libs/k8s/issues/132 the issue is still present.

Unless I add the block suggested [here](https://github.com/jsonnet-libs/k8s/issues/132#issuecomment-1066696379) I get 
```
Error: evaluating jsonnet: RUNTIME ERROR: max stack frames exceeded.
        Field "#mixin"
        Field "mixin"
        Field "mixin"
        Field "mixin"
        Field "mixin"
        Field "mixin"
        Field "mixin"
        Field "mixin"
        Field "mixin"
        Field "mixin"
        ...
        Field "nodeAffinity"
        Field "affinity"
        Field "spec"
        Field "template"
        Field "spec"
        Field "daemonSet"
        Field "v1beta1"
        Field "extensions"
        Field "test"
        During manifestation
```

**Comment by xvzf** [comment]
@irizzant I checked your example and It seems it's linked to this issue https://github.com/grafana/jsonnet-libs/pull/800

**Comment by irizzant** [comment]
@xvzf ok, so until https://github.com/grafana/jsonnet-libs/pull/800 is merged I will use [this](https://github.com/jsonnet-libs/k8s/issues/132#issuecomment-1066696379) workaround

**Comment by mplzik** [comment]
Bump :-) Kubernetes 1.21 is not supported as of 2022-06-28; so AFAIK, using jsonnet-libs is not problematic for any supported Kubernetes version.

**Comment by xvzf** [comment]
Upstream is merged @irizzant :)

**Comment by irizzant** [comment]
Good news @xvzf thanks
