### ISSUE TITLE
IDE Completion / Interface Processes?

### ISSUE THREAD

**Issue by midnightconman** [jsonnet-libs/k8s#27]
I have been using k8s-alpha and ksonnet for a while, it can be annoying to work with based on the complexity of objects and it's structure. Do you guys have any recommendations for how to deal with this library from an IDE perspective? Can you  possibly talk about how developers in your company interface with this library (possibly any tooling that you use to aid in field discovery)?

**Comment by xvzf** [comment]
Hi

For now it is mostly just vim + knowing it. I think it'd be fairly easy to build an autocompletion based on the docsonnet. I started looking into LSPs but that's sort of a mystery for me right now. Possibly the vim omnicomplete is another option

**Comment by Duologic** [comment]
The generator project might be able to render the source files needed for a language server to work, but the language server is out-of-scope for this project. I'd suggest we take this to the discussions section on the Tanka repo (related issue: https://github.com/grafana/tanka/discussions/503) or the different channels in the wider [Jsonnet community](https://jsonnet.org/learning/community.html).

As for finding docs, with recent changes to the generator here, we rendered new docs (for example: https://jsonnet-libs.github.io/k8s-libsonnet/) that hopefully have a more user friendly experience now (contributions welcome).
