### ISSUE TITLE
Better documentation and explanation of object shapes

### ISSUE THREAD

**Issue by ghostsquad** [jsonnet-libs/k8s#295]
An example is:
https://github.com/jsonnet-libs/k8s-libsonnet/blob/main/docs/1.26/core/v1/service.md#fn-new

what is `selector` or `ports` supposed to look like?

Might be nice to include links back to the api reference documentation, e.g. https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#servicespec-v1-core

**Comment by Duologic** [comment]
I'd love to see a PR for this but closing this as to not keep issues open forever. Feel free to reopen in case you feel like working on this.
