### ISSUE TITLE
Support for CustomResourceDefinitions

### ISSUE THREAD

**Issue by bgagnon** [jsonnet-libs/k8s#3]
Would it be feasible for this generator to support generation of Jsonnet mixins given a CustomResourceDefinition that contains an OpenAPI schema?

Ideally, it would take the CRD manifest as input (JSON or YAML), but I suppose it could also fetch the OpenAPI schema from a running K8S API server where the CRD has been installaed.

**Comment by sh0rez** [comment]
Yes, that's very much possible! The generator is generic enough to support it in theory, though there are some rough edges that need to be fixed first.

My priority is to get it considerably stable first, but it is on the feature roadmap!

**Comment by bgagnon** [comment]
Awesome :) Here are some CRD collections we have in mind:

* [coreos/prometheus-operator](https://github.com/coreos/prometheus-operator)
* [projectcontour/contour](https://github.com/projectcontour/contour)

**Comment by xvzf** [comment]
Any updates on this regarding a timeline? Or a way to support? :)

**Comment by hamishforbes** [comment]
Adding a +1 to this, just starting looking at [ECK](https://www.elastic.co/guide/en/cloud-on-k8s/current/k8s-deploy-eck.html) and want to generate their custom resources in Tanka :)

**Comment by groodt** [comment]
+1 for this

**Comment by xvzf** [comment]
@bgagnon @hamishforbes @groodt Would you mind checking out my branch & test it for your CRDs?  It requires a live control plane (for now). It works fine for the Istio 1.7 CRDs

**Comment by groodt** [comment]
I was able to generate something for Argo Workflows by doing the following:

* Clone https://github.com/argoproj/argo
* `cd argo/api/openapi-spec`
*  `python3 -m http.server 8001`
* Different terminal
* Clone this PR https://github.com/jsonnet-libs/k8s/pull/13
* `cd k8s`
* `go build`
* Edit config.yml to add Argo swagger.json (see below)
* `./k8s`

config.yml

```
# Argo
- output: 'gen/local-argo'
  openapi: http://localhost:8001/swagger.json
  prefix: io.argoproj
  patchDir: custom/argo
  extensionDir: extensions/argo
```

It generates a bunch of jsonnet, but it broadly seems successful on these complex CRDs.

**Comment by xvzf** [comment]
@groodt wdym by surpassing resources?

**Comment by groodt** [comment]
> @groodt wdym by surpassing resources?

I meant "suppress" or hide. There seem to be some not very valuable resources in the Argo swagger such as `io.argoproj.workflow.v1alpha1.ArchivedWorkflowDeletedResponse`

I guess this tool is doing the correct thing by including them and it's up to the user to not use them. The main resources/entities of value seem to be generated ok.

**Comment by xvzf** [comment]
Okay I see! We could define an exclude list if that helps?

**Comment by groodt** [comment]
That functionality might be useful. No need for now. Let’s see if there’s
demand.
