### ISSUE TITLE
bazel rules

### ISSUE THREAD

**Issue by Geethree** [jsonnet-libs/k8s#37]
Would this group be open for me adding a bazel build file, some rules and macros?

Currently, I am pulling in k8s-alpha via a bazel [http_archive](https://docs.bazel.build/versions/main/repo/http.html#http_archive) and creating a [jsonnet_library](https://github.com/bazelbuild/rules_jsonnet#jsonnet_library) out of them. But it would be lovely to just be able to grab this repository and build them directly.

**Comment by xvzf** [comment]
Since there is no build system yet - just do a PR and we can go from that?

**Comment by Duologic** [comment]
I was planning to automate it through Github actions for now. I'm not familiar with Bazel.

**Comment by Duologic** [comment]
The github actions are now in place.

The most common way to pull in jsonnet libraries is currently through [jsonnet-bundler](https://github.com/jsonnet-bundler/jsonnet-bundler/), this also does leverages the http-archive afaik. Maybe a `jsonnet_bundler` bazel rule could be a thing? Or maybe the `jsonnet_library` could build-in the `http_archive` rule?

My main question is: why put the burden of integrating into someone else's CI system on the source files?

**Comment by Duologic** [comment]
It is a common pattern to have this wrapper in `lib/k.libsonnet`, for example this works well with [ksonnet-util](https://github.com/grafana/jsonnet-libs/blob/master/ksonnet-util/k-compat.libsonnet#L3) on which quite a bit of libraries depend upon.

**Comment by Duologic** [comment]
Judging on above discussion, I believe the original question was answered with a suggested solution by @0xIDANT. I think we can close it based on that.
