### ISSUE TITLE
Kubernetes 1.23 compatibility

### ISSUE THREAD

**Issue by Its-Alex** [jsonnet-libs/k8s#417]
Hi :wave: 

I would like to use k8s-libsonnet with kubernetes 1.23, unfortunately I have an error when I tried to init repository:

```sh
tk init -f --k8s=1.23
GET https://github.com/jsonnet-libs/docsonnet/archive/6ac6c69685b8c29c54515448eaca583da2d88150.tar.gz 200
GET https://github.com/jsonnet-libs/k8s-libsonnet/archive/bf9a62cfd32a58c071b8410bfcdec058475dd25e.tar.gz 200
panic: rename /tanka/vendor/.tmp/ea36fa71e5e53902cdbd8ef95725577a143250468/1.23 /tanka/vendor/github.com/jsonnet-libs/k8s-libsonnet/1.23: no such file or directory

goroutine 1 [running]:
github.com/jsonnet-bundler/jsonnet-bundler/pkg.(*GitPackage).Install(0xc00025a050, {0x829ee8?, 0xc00001c0e8}, {0xc00022e240, 0x2a}, {0xc00001e780, 0x52}, {0x7fff3872ed1d, 0x4})
        /home/metalmatze/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/git.go:228 +0x1a9d
github.com/jsonnet-bundler/jsonnet-bundler/pkg.download({{0xc000010500, 0x0}, {0x7fff3872ed1d, 0x4}, {0x0, 0x0}, 0x0, {0x0, 0x0}}, {0xc00001e780, ...}, ...)
        /home/metalmatze/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go:309 +0x3b1
github.com/jsonnet-bundler/jsonnet-bundler/pkg.ensure(0x51?, {0xc00001e780, 0x52}, {0x0, 0x0}, 0x0?)
        /home/metalmatze/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go:234 +0x61d
github.com/jsonnet-bundler/jsonnet-bundler/pkg.Ensure({0xc0000a7fb0?, 0x0?}, {0xc00001e780, 0x52}, 0x0?)
        /home/metalmatze/src/github.com/jsonnet-bundler/jsonnet-bundler/pkg/packages.go:55 +0x54
main.installCommand({0xc000026004?, 0x7a64a2?}, {0x79370b, 0x6}, {0xc000050500, 0x3, 0x0?}, 0x0, {0x0, 0x0})
        /home/metalmatze/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/install.go:85 +0x46d
main.Main()
        /home/metalmatze/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:87 +0xd27
main.main()
        /home/metalmatze/src/github.com/jsonnet-bundler/jsonnet-bundler/cmd/jb/main.go:39 +0x19
Installing k.libsonnet: exit status 2
Directory structure set up! Remember to configure the API endpoint:
`tk env set environments/default --server=https://127.0.0.1:6443`
Errors occurred while initializing the project. Check the above logs for details.
```

Can you help me setup the repository? Thanks in advance!

**Comment by Its-Alex** [comment]
Is it possible to have a documentation with kubernetes version support? And drop notice? That was difficult to understand that the support for this version has been dropped.

**Comment by xvzf** [comment]
Hey

We usually follow the supported kubernetes versions, 1.23 is out of support since March 2023 - you can use an older version of the library which still contains the 1.23 libs.

**Comment by Its-Alex** [comment]
@xvzf, perhaps consider adding it to the readme, possibly including instructions on how to use an older version?

Otherwise, you can close this issue. Thank you for your response.

**Comment by Duologic** [comment]
You can look at the [commit history](https://github.com/jsonnet-libs/k8s-libsonnet/commits/main/), browsing each commit should surface quickly when the last version of 1.23 was created, took me 1min: https://github.com/jsonnet-libs/k8s-libsonnet/tree/5c83a9a2b08fa055cfc62d9f59270161dd729596

**Comment by Its-Alex** [comment]
@Duologic Upon exploring the repository, I encountered an older version of Kubernetes and faced an issue during the Tanka init process. As I have not previously contributed to the repository, I am unfamiliar with the code. I believe that adding documentation to explain which versions are deprecated or located in older commits would save time for all users and make the installation of the jsonnet k8s library easier. While navigating the commit history is straightforward, understanding how the repository functions, browsing through commits, and manually modifying the jsonnet bundler lock file can be challenging for new users.
