### ISSUE TITLE
withApiVersion missing for autoscaling/v2beta2 HorizontalPodAutoscaler

### ISSUE THREAD

**Issue by xvzf** [jsonnet-libs/k8s#55]
Seems this is not generated (but required by Kubernetes); on my cluster it's been in the OpenAPI specs so it might be a bug in the template generation.

https://jsonnet-libs.github.io/k8s-libsonnet/1.21/autoscaling/v2beta2/horizontalPodAutoscaler/#obj-specscaletargetref

**Comment by julienduchesne** [comment]
withApiVersion is now generated for nested properties: https://github.com/jsonnet-libs/k8s-libsonnet/blob/main/docs/1.21/autoscaling/v2beta2/horizontalPodAutoscaler.md#fn-specscaletargetrefwithapiversion
