### ISSUE TITLE
Problems importing CRDs with Helm variables in metadata - Linkerd

### ISSUE THREAD

**Issue by andersosthus** [jsonnet-libs/k8s#92]
Hi,

I'm trying to generate jsonnet-libs for the Linkerd2 CRDs. They are published as part of a Helm template, and they use some Helm specific things in the `metadata` section of the CRDs. This of course, causes the generation to fail.

Is there any way we could either "reset" the metadata section (basically just set it to {}), or somehow ignore these kind of values?

Example CRD is here: https://raw.githubusercontent.com/linkerd/linkerd2/release/stable-2.11/charts/linkerd2/templates/policy-crd.yaml

**Comment by Duologic** [comment]
Would you mind creating an upstream issue? Even though widespread, I'd argue that not everyone uses Helm.

The process here could also be extended to support Helm, of course. It would be much nicer to have access to the CRDs directly.

**Comment by Duologic** [comment]
I believe we can close this as not further action is needed.
